site_name: CS Learning
site_url: https://tenshi0x0.github.io/CS-learning/
site_author: Tenshi
theme:
  name: material

  favicon: assets/icons/icon-pen-tip.png
  logo: assets/icons/icon-pen-tip.png

  # 支持页面 亮/暗
  palette:
    # 暗色模式（默认）
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: 切换到亮色模式
    
    # 亮色模式
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: 切换到暗色模式
  features:
    - navigation.tabs           # 顶部标签导航
  #   - navigation.tabs.sticky    # 标签固定
  #   - navigation.sections       # 侧边栏分组
  #   - navigation.expand         # 默认展开
  #   - navigation.path          # 面包屑导航
    - navigation.top           # 返回顶部
  #   - navigation.indexes       # 章节索引页
    - toc.follow              # 目录跟随
    - search.suggest          # 搜索建议
    - search.highlight        # 搜索高亮
    - content.code.copy  # 添加复制按钮
    - content.code.annotate  # 代码注释

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 首页:
    - 前言: index.md
    - 友链: friendlyURL.md 

  - 人工智能:
    - 强化学习:
      - MathFoundationRL: src/AI/RL/MathFoundationRL.md
  
  - 杂项:
    - 搭建博客:
      - 搭建 wiki: src/Miscellaneous/Setting_up_a_wiki.md
      # - 临时: index.md